### ISSUE TITLE
接受自定义的"origin"域,以及CORS支持

### ISSUE THREAD

**Issue by Javran** [poooi/poi-server#1]
正在实现 [KC3改](https://github.com/KC3Kai/KC3Kai) 的统计数据发送支持,由于这是个chrome插件,[无法自定义UA](http://stackoverflow.com/questions/5771878/jquery-ajax-request-change-user-agent/5862744#5862744)
故希望能支持自定义 `origin` 域: 服务端接收数据的时候若这个域已经存在便不再以UA覆盖. 不知是否可行?

此外是否能加一下服务器[对CORS的支持](http://enable-cors.org/server.html)? 如链接,最简单的方法就是在response header里设置

```
Access-Control-Allow-Origin: *
```

谢谢~

**Comment by hanzhao** [comment]
现在的 header
nya@biu$  curl -i poi.0u0.moe
HTTP/1.1 200 OK
Server: nginx/1.7.3
Date: Sun, 18 Oct 2015 04:51:14 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 435
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type

<!DOCTYPE html><html lang="zh"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>Index</title><link rel="stylesheet" href="/components/amazeui/dist/css/amazeui.min.css"><link rel="stylesheet" href="/components/css/style.css"><script src="/components/react/react.min.js"></script><script src="/components/amazeui-react/dist/amazeui.react.min.js"></script></head><body><h1>It works!</h1></body></html>%

**Comment by Javran** [comment]
![2015-10-18_010021_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/10562625/b49d32a0-7533-11e5-8f1d-ac8540f9dfbd.png)
试着开发了两次,这次没有错误信息了,确认下是否收到?

**Comment by hanzhao** [comment]
> db.createitemrecords.find({origin: 'KC3Kai 21.2'})
> { "secretary" : 196, "teitokuLv" : 102, "successful" : true, "itemId" : 23, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623274086643c915458b31b"), "items" : [  20,  30,  10,  109 ], "__v" : 0 }
> { "secretary" : 196, "teitokuLv" : 102, "successful" : true, "itemId" : 22, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623274a86643c915458b38a"), "items" : [  20,  30,  10,  109 ], "__v" : 0 }

**Comment by hanzhao** [comment]
https://github.com/poooi/poi-server/wiki
一些基本信息 如果不全的话可以跟我说下。

**Comment by Javran** [comment]
行,不过既然github wiki权限设的是所有人都可以编辑,趁现在还有些印象我帮着修改一下吧.

**Comment by Javran** [comment]
wiki改差不多了,知道的基本就是这些了.

另外现在应该有些建造和掉落的数据了,是否可以再帮忙查看一下?

**Comment by hanzhao** [comment]
> use poi-production
> switched to db poi-production
> db.createitemrecords.find({origin: 'KC3Kai 21.2'})
> { "secretary" : 196, "teitokuLv" : 102, "successful" : true, "itemId" : 23, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623274086643c915458b31b"), "items" : [  20,  30,  10,  109 ], "__v" : 0 }
> { "secretary" : 196, "teitokuLv" : 102, "successful" : true, "itemId" : 22, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623274a86643c915458b38a"), "items" : [  20,  30,  10,  109 ], "__v" : 0 }
> db.createshiprecords.find({origin: 'KC3Kai 21.2'})
> { "kdockId" : 0, "secretary" : 187, "teitokuLv" : 102, "largeFlag" : false, "highspeed" : 0, "shipId" : 68, "origin" : "KC3Kai 21.2", "_id" : ObjectId("562382487642682a56e088d1"), "items" : [  250,  31,  200,  30,  1 ], "__v" : 0 }
> { "kdockId" : 1, "secretary" : 187, "teitokuLv" : 102, "largeFlag" : false, "highspeed" : 1, "shipId" : 24, "origin" : "KC3Kai 21.2", "_id" : ObjectId("562382797642682a56e08ae6"), "items" : [  250,  31,  200,  30,  1 ], "__v" : 0 }
> { "kdockId" : 1, "secretary" : 187, "teitokuLv" : 102, "largeFlag" : true, "highspeed" : 0, "shipId" : 70, "origin" : "KC3Kai 21.2", "_id" : ObjectId("562382997642682a56e08c56"), "items" : [  1500,  1500,  2000,  1000,  1 ], "__v" : 0 }
> db.dropshiprecords.find({origin: 'KC3Kai 21.2'})
> { "mapId" : 11, "cellId" : 1, "isBoss" : false, "enemyFormation" : 1, "shipId" : 11, "quest" : "鎮守府正面海域", "enemy" : "敵偵察艦", "mapLv" : 0, "rank" : "S", "teitokuLv" : 102, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623834e7642682a56e09425"), "enemyShips" : [  501,  -1,  -1,  -1,  -1,  -1 ], "__v" : 0 }
> { "mapId" : 11, "cellId" : 3, "isBoss" : true, "enemyFormation" : 0, "shipId" : 97, "quest" : "鎮守府正面海域", "enemy" : "敵主力艦隊", "mapLv" : 0, "rank" : "A", "teitokuLv" : 102, "origin" : "KC3Kai 21.2", "_id" : ObjectId("562383a17642682a56e0979b"), "enemyShips" : [  505,  503,  502,  502,  -1,  -1 ], "__v" : 0 }
> { "mapId" : 43, "cellId" : 14, "isBoss" : false, "enemyFormation" : 4, "shipId" : 69, "quest" : "リランカ島空襲", "enemy" : "敵潜水艦隊", "mapLv" : 0, "rank" : "S", "teitokuLv" : 102, "origin" : "KC3Kai 21.2", "_id" : ObjectId("56239fdf7642682a56e1f2bc"), "enemyShips" : [  532,  530,  530,  530,  518,  519 ], "__v" : 0 }
> { "mapId" : 43, "cellId" : 7, "isBoss" : false, "enemyFormation" : 4, "shipId" : 64, "quest" : "リランカ島空襲", "enemy" : "敵潜水艦隊", "mapLv" : 0, "rank" : "S", "teitokuLv" : 102, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623a03b7642682a56e1f73a"), "enemyShips" : [  532,  530,  530,  530,  518,  519 ], "__v" : 0 }
> { "mapId" : 43, "cellId" : 14, "isBoss" : false, "enemyFormation" : 5, "shipId" : -1, "quest" : "リランカ島空襲", "enemy" : "敵潜水艦隊", "mapLv" : 0, "rank" : "S", "teitokuLv" : 102, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623beb07642682a56e3850d"), "enemyShips" : [  532,  532,  530,  530,  530,  526 ], "__v" : 0 }
> { "mapId" : 43, "cellId" : 7, "isBoss" : false, "enemyFormation" : 4, "shipId" : 66, "quest" : "リランカ島空襲", "enemy" : "敵潜水艦隊", "mapLv" : 0, "rank" : "S", "teitokuLv" : 102, "origin" : "KC3Kai 21.2", "_id" : ObjectId("5623bf1d7642682a56e38995"), "enemyShips" : [  532,  530,  530,  530,  518,  519 ], "__v" : 0 }

**Comment by Javran** [comment]
ok看来都没问题了
谢谢~
