### ISSUE TITLE
Failed dump

### ISSUE THREAD

**Issue by Acrone** [poooi/poi-server#10]
Hello again,

It appears that there was an error during the database dump at 10:59 PM JST yesterday. The dropshiprecords.bson collection was not included in the dump, and has not been updated since that time. Looks like the database dump schedule has stalled as a result.

Kind regards,
Acrone

**Comment by yukixz** [comment]
@Acrone I add reporting 6-5 boss drop yesterday. It may break mongodb.

**Comment by yukixz** [comment]
_Removed_

**Comment by yukixz** [comment]
Manual dump work porperly...

**Comment by yukixz** [comment]
hmm... Someone edit crontab wrongly. Make cron dump every minute.
Fixed now.

**Comment by Acrone** [comment]
Looks good on my end.
Thank you for resolving this so quickly.
