### ISSUE TITLE
Database dump not available

### ISSUE THREAD

**Issue by Acrone** [poooi/poi-server#24]
Hello there,

Sorry to bother you, but after the monthly reset the database dump no longer seems to be [available](http://i.imgur.com/ZL7Wrel.png).

Kind regards

**Comment by hanzhao** [comment]
Hi,
We have enabled gzip for our dump to reduce storage/network cost, and the dump is splitted into different files based on its collection. For downloading, use https://poi.0u0.moe/dump/{dropshiprecords,createshiprecords,createitemrecords,selectrankrecords,passeventrecords,quests}.gz .
Sorry for any inconvenience.

**Comment by Acrone** [comment]
Ah that explains it. There was no real inconvenience.
Thank you for your quick response!
