### ISSUE TITLE
remodelitemrecords

### ISSUE THREAD

**Issue by Acrone** [poooi/poi-server#29]
Hello there,

Not long ago the database dumps were altered from the single compressed file to separate archives for each collection.

The available archives after the change were listed as:
- dropshiprecords.gz
- createshiprecords.gz
- createitemrecords.gz
- selectrankrecords.gz
- passeventrecords.gz
- quests.gz

What I was wondering was back before the database dump change, the dumps used to have a _remodelitemrecords_ collection for item remodelling reports. Is this not available anymore?

Kind regards

**Comment by yukixz** [comment]
`remodelitemrecords` collections is ended for 2 month, so it's not included in dump. You can download a historical dump from http://poi.0u0.moe/dump/remodelitemrecords.tar.xz

BTW, full collections list:
- aaci.csv.gz
- createitemrecords.gz
- createshiprecords.gz
- dropshiprecords.gz
- passeventrecords.gz
- reciperecords.gz
- selectrankrecords.gz

**Comment by KagamiChan** [comment]
to add up, quests should be quests.csv.gz now
