### ISSUE TITLE
统计明石改修成功率

### ISSUE THREAD

**Issue by yukixz** [poooi/poi-server#3]
数据：
装备 api_slotitem_id, api_level
明石 api_ship_id, api_lv, api_cond
僚舰 api_ship_id, api_lv, api_cond

**Comment by yukixz** [comment]
PR: https://github.com/poooi/poi-server/pull/4, https://github.com/poooi/plugin-report/pull/4

**Comment by dkwingsmt** [comment]
这 pr close 了呀
