### ISSUE TITLE
Support conditional drops?

### ISSUE THREAD

**Issue by gakada** [poooi/poi-server#36]
That is, drops (or their rates) that depend on conditions, such as if player already has a ship (or how many) or if player already dropped a ship from a node.

For example

* `api_member_id` / `_teitokuId` can be added to `DropShipRecord`, similarly to `SelectRankRecord` and `PassEventRecord`. That can be used to check if it is possible to drop multiple instances of a ship from a node.
* For a ship X drop, send how many instances of X player currently has. That can be used to reject "X doesn't drop if player already has X". Some problems here:
  * Remodels of X.
  * Generally, the whole ship list state should be submitted with each drop (how it is implemented [here](https://github.com/KC3Kai/KC3Kai/blob/master/src/library/modules/TsunDBSubmission.js)), which I'm not suggesting, just as a note.

**Comment by KagamiChan** [comment]
It seems that we could do a shasum on player ID to conform to latest regulations

On counting remodels, we do not have to submit whole ship list. There're several implementations of counting "unique" ships, and https://github.com/poooi/plugin-ship-info/blob/master/views/selectors.es#L475 is an example of them

I'll be glad to see a PR

**Comment by gakada** [comment]
I was thinking about applying a hash, but will it really serve any function? Considering it won't be pre-image resistant, since for any function `f` and hash `h` solving `h = f(id)` for `id` is easy, since looping over numeric IDs < 21000000 is fast. Solving something like `f(id + name + ...)` is slower but probably still too fast practically.

For counting, I mean generally full ship lists are required for accurate (conditional) drop rates, need to know how many X player has on both X drops and non drops, e.g., with `m` X in possession `i` X drops and `n` non drops gives `p(X, m) = i / (i + n + ...)`, full lists are required for `n` since non drop is just `-1` and X is unknown. So to keep it simple, can only send form counters on X drops, something like `[number of base forms in possession, number of 1st remodel forms, ...]`, ignoring non drops.

**Comment by gakada** [comment]
maybe `sha(api_member_id + api_nickname + api_nickname_id)` (SHA1?)

**Comment by KagamiChan** [comment]
You're right, cracking the player id hash is something cheap

I see what you mean. The whole ship list is required for accurate statistics if no ship is specific. Then we'll be collecting too much information from players and an explicit acknowledgement from user is a must. I'm afraid this is not suitable for our reporter.

**Comment by gakada** [comment]
Yes, in that case I will see about making a PR for 
```ts
teitokuHash: String, // e.g., api_member_id + api_nickname + api_nickname_id hash should be hard to crack
shipCounter: Number or [Number] // just for base or remodel counters for a dropped ship
```

**Comment by KagamiChan** [comment]
Let's make `shipCounter` of type `number[]` at any time so that it could be consistent

**Comment by KagamiChan** [comment]
I'm ready to help if you encounter problems in making the PR

**Comment by KagamiChan** [comment]
seems settled

**Comment by gakada** [comment]
For full analysis (like possible conditions between unrelated ships, https://twitter.com/FlatIsNice/status/1042162744408137728, or just accurate rates) `fleetCounts` is still required. Though it will add approximately 100 bytes to each record (1/8 of log2 of ((600, 300)), also x10 for any encoding overhead).
