### ISSUE TITLE
Dump File Formats

### ISSUE THREAD

**Issue by Divinity123** [poooi/poi-server#42]
Hello there. I have a question regarding format of dump files I get from the server. I wanted to analyse drop rates when owning duplication but it is not obvious to me how should I open those files (dropshiprecords in particular) at all. Can someone enlighten me on this? Many thanks.

EDIT: I have figured it all out. Instead of bson, the dump is simply a binary version of json.

**Comment by KagamiChan** [comment]
The dropshiprecords is in bson format, it is produced via [mongodump](https://docs.mongodb.com/manual/reference/program/mongodump/).

While we could convert it to json, an efficient alternative could be setting up a local mongo server and importing the data with [mongorestore](https://docs.mongodb.com/manual/reference/program/mongorestore/), and querying data with the mongo binding for your preferred language

**Comment by Divinity123** [comment]
Thank you so much for your reply! Maybe you should put this information in https://github.com/poooi/poi-server/wiki so that others know how to handle the data?

**Comment by gakada** [comment]
I find it more convenient and efficient (as with full reduce anything will need to do a full read cycle first, be it from disk or tmpfs, latter is faster of course, simply reading and reducing can be faster than doing `mongorestore`, waiting on `mongod`, etc.) to read BSON directly as [binary file](http://bsonspec.org/spec.html). Initially was C++, but recently I'm using [stream-bson](https://www.npmjs.com/package/stream-bson) package that I did in [Node.js](https://nodejs.org/en/), also work fine, something like
```js
const StreamBSON = require('stream-bson')

const data = {}

const onRecord = record => {
  // record is just JS object from https://www.npmjs.com/package/bson
}

const onFinish = () => {
  // data is ready
}

createReadStream(bsonPath)
  .pipe(new StreamBSON({ archive: true }))
  .on('data', onRecord)
  .on('finish', onFinish)
  .on('error', e => console.log(e.toString()))
```
Also can be extended to do conversion to/from JSON, which can be useful for small BSON files.

**Comment by Divinity123** [comment]
Fair enough. I mean I am fine doing all the post-processing myself and I really appreciate your work. Just that I need the right information to begin with. Anyway, thank you again for your clarification, and wish you good luck in the event!

**Comment by KagamiChan** [comment]
@Divinity123 good catch. We did not realize this before.

Added some instructions on wiki page
