### ISSUE TITLE
How can I import dumped data with mongostore

### ISSUE THREAD

**Issue by HeliumOctahelide** [poooi/poi-server#46]
I downloaded data createitemrecords.gz, unzipped it to dir /root/data, and tried to use command `mongorestore -h localhost -d createitemrecords /root/data` to import it. But it returned result like this

2018-10-27T03:58:22.094+0800 I NETWORK  [listener] connection accepted from 127.0.0.1:37482 #3 (1 connection now open)
2018-10-27T03:58:22.095+0800    the --db and --collection args should only be used when restoring from a BSON file. Other uses are deprecated and will not exist in the future; use --nsInclude instead
2018-10-27T03:58:22.095+0800    building a list of collections to restore from /root/data dir
2018-10-27T03:58:22.095+0800    don't know what to do with file "/root/data/createitemrecords", skipping...
2018-10-27T03:58:22.096+0800    done

How can I read this data correctly?

**Comment by gakada** [comment]
First, create a directory, e.g., `path/to/db`, then start MongoDB server on that directory
```
mongod --dbpath path/to/db
```
Then (probably in another terminal) restore gzipped data (`path/to/createitemrecords.gz`) to that directory
```
mongorestore --gzip --archive=path/to/createitemrecords.gz -d poi-production
```
Then query from the DB (using a MongoDB GUI program or a MongoDB binding library for your language of choice). Here is an example for `dropshiprecords.gz` https://github.com/kcwiki/repo/blob/old2/poi/poidb.sh, https://github.com/kcwiki/repo/blob/old2/poi/poidb-data.js.

As an alternative method, can also read it directly as BSON (inside MongoDB archive) without using MongoDB server, e.g., https://www.npmjs.com/package/stream-bson.

**Comment by HeliumOctahelide** [comment]
> First, create a directory, e.g., `path/to/db`, then start MongoDB server on that directory
> 
> ```
> mongod --dbpath path/to/db
> ```
> Then (probably in another terminal) restore gzipped data (`path/to/createitemrecords.gz`) to that directory
> 
> ```
> mongorestore --gzip --archive=path/to/createitemrecords.gz -d poi-production
> ```
> Then query from the DB (using a MongoDB GUI program or a MongoDB binding library for your language of choice). Here is an example for `dropshiprecords.gz` https://github.com/kcwiki/repo/blob/old2/poi/poidb.sh, https://github.com/kcwiki/repo/blob/old2/poi/poidb-data.js.
> 
> As an alternative method, can also read it directly as BSON (inside MongoDB archive) without using MongoDB server, e.g., https://www.npmjs.com/package/stream-bson.

Thx. It works.

**Comment by gakada** [comment]
Going to add a short piece on the wiki for those commands.
