### ISSUE TITLE
[RFC] equipment bonus collection

### ISSUE THREAD

**Issue by gakada** [poooi/poi-server#48]
~~There is a collection for figuring out ship evasion/ASW/LoS stats based on different level values. Similarly, when a ship is equipped with some equipment resulting stats is stats without equipment + equipment stats (visible in `api_start2`) + unknown [bonuses](https://drive.google.com/open?id=1bInH11S_xKdaKP754bB7SYh-di9gGzcXkiQPvGuzCpg) depending on ship and equipment. So a new collection can be used to record ship stats and used equipment on equipment changes to automatically figure out those bonuses.~~

Available in client code anyway.

**Comment by gakada** [comment]
Btw is [`ShipStat`](https://github.com/poooi/poi-server/blob/master/models/report/ship-stat.es) available as dump?

**Comment by KagamiChan** [comment]
yes, ship stat is available
https://poi.0u0.moe/dump/ship-stat.json

**Comment by gakada** [comment]
In addition, it can store stock equipment of new and remodeled ships (as, for example, they changed stock equipment of many destroyers not long ago).
