### ISSUE TITLE
Request to use data

### ISSUE THREAD

**Issue by Acrone** [poooi/poi-server#8]
Hello poi-server team,

I am writing to you today to make a formal request to use of the data provided via your current poidb dumps.

Over the past few weeks I have been working on a small KanColle site that provides statistics to the english community. While the kcwiki [drop page](https://db.kcwiki.moe/drop/) is a fantastic resource, the language barrier is a problem for some so I decided to take up this project.

A few weeks ago I made a request with the poi-statistics team to use some of their data, which was given, however I was later informed of your data dumps and have been wanting to use them directly instead of scraping straight from the kcwiki front end.

For the past few weeks I have been downloading the database dump every few days and making use of the statistics as a result. This was a great help for us english players when Uranami was released as I was able to give them drop results before the kcwiki [drop page](https://db.kcwiki.moe/drop/ship/486/SAB.html) had updated to display them.

I wanted to ask you directly if it is okay for me to continue to use the data you collect so that I can utilize it and offer statistics for the english community.

If you are interested, you are able to see what I have done so far with my site [here](http://kc.acr.one/stats/). It is still in its early stages, but I am hoping to one day provide to the english community what the kcwiki does for the non-english community.

Kind regards,
Acrone

**Comment by dkwingsmt** [comment]
Hi Acrone, 

Thank you for your effort to provide this service to English communities. It's always been our pleasure to help more people, including both players and volunteer contributors. Yes, you are allowed to use the dumped database for analysis, with the following restrictions:
1. Redistributing the database or any unprocessed data is strictly prohibited.
2. The copyright of analysis results belongs to the analyser.

Overall the line is "Don't do evil". Anyway, feel free to contact us if you have any other questions or suggestions, either about the data collection or poi.

Good luck!

Sincerely,
Tong from poi

**Comment by dkwingsmt** [comment]
Sorry, here's a correction to the second term. It should be 

> The copyright of analysis results belongs to the analyser

**Comment by Acrone** [comment]
Hello Tong,

Thank you very much for your approval. This is greatly appreciated!

I did have some general questions in regards to the database, but I can't quite recall them at the moment. I'll remember them when I come across them again I'm sure.

Until then, thank you again, and all the best to yourself and the rest of the team.

Kind regards,
Acrone
